Repository grails/grails-forge, pull requests merged in 2024-11, with the labels that each got.

#418 make grails-wrapper a default feature
  grails-forge-core/src/main/java/org/grails/forge/feature/grailsWrapper/GrailsWrapper.java
  grails-forge-core/src/main/java/org/grails/forge/feature/grailsWrapper/GrailsWrapperFeature.java
  grails-forge-core/src/test/groovy/org/grails/forge/feature/grailsWrapper/GrailsWrapperSpec.groovy
Labels: feature

#416 chore: aligned .gitignore to the one used by Spring 3.4.0-SNAPSHOT
  grails-forge-core/src/main/java/org/grails/forge/feature/build/gitignore.rocker.raw
Labels: chore, maintenance

#429 Temporarily disable docs
  .github/workflows/release.yml
Labels: documentation

#430 Revert temporary publishing adjustments and remove macOS ARM from SDKMAN releases
  .github/workflows/release.yml
  grails-cli/build.gradle
Labels: revert
