Repository grails/grails-forge, pull requests merged in 2024-04, with the labels that each got.

#326 chore(build): Migrate to Develocity build cache connector
  .github/workflows/mavenCentral.yml
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
  settings.gradle
Labels: chore, ci, maintenance, build

#327 fix(deps): Upgrade to grails-quartz 3.0.0
  grails-forge-core/src/main/resources/pom.xml
  grails-forge-core/src/test/groovy/org/grails/forge/feature/grails/GrailsGradlePluginSpec.groovy
Labels: bug, deps

#334 fix: update web-driver-binaries version
  grails-forge-core/src/main/java/org/grails/forge/feature/test/template/webdriverBinariesPlugin.rocker.raw
  grails-forge-core/src/test/groovy/org/grails/forge/feature/test/GebSpec.groovy
Labels: bug

#336 chore(release): update workflow configurations
  .github/workflows/release.yml
Labels: chore, maintenance
