Repository grails/grails-forge, pull requests merged in 2024-08, with the labels that each got.

#343 fix(build): Update build and CI workflows
  .github/workflows/deploy.yml
  .github/workflows/mavenCentral.yml
  .github/workflows/release-notes.yml
  .github/workflows/release.yml
  .github/workflows/sdkman.yml
  .github/workflows/snapshot.yml
  grails-cli/build.gradle
  grails-cli/src/test/groovy/org/grails/forge/cli/CommandSpec.groovy
  grails-forge-core/src/main/java/org/grails/forge/util/IOFeatureUtil.java
Labels: bug, maintenance, test

#349 fix: Remove failing iedriverserver
  grails-forge-core/src/main/java/org/grails/forge/feature/test/template/webdriverBinariesPlugin.rocker.raw
  grails-forge-core/src/test/groovy/org/grails/forge/feature/test/GebSpec.groovy
Labels: bug

#356 Update version for mongo driver in test
  grails-forge-core/src/test/groovy/org/grails/forge/feature/database/MongoSyncSpec.groovy
Labels: maintenance, test

#344 fix: update the GitHub Actions templates for building, testing apps
  grails-forge-core/src/main/java/org/grails/forge/feature/github/workflows/plain/templates/plainGithubWorkflow.rocker.raw
  grails-forge-core/src/main/java/org/grails/forge/feature/github/workflows/templates/javaSetup.rocker.raw
Labels: bug, maintenance, build, test

#359 Adjust change on IOFeatureUtil.java to fix build of grails-forge-core on Java 11
  grails-forge-core/src/main/java/org/grails/forge/util/IOFeatureUtil.java
Labels: bug, maintenance, feature, build

#342 fix: Remove default controller scope from app config
  grails-forge-core/src/main/java/org/grails/forge/feature/web/GrailsWeb.java
  grails-forge-core/src/test/groovy/org/grails/forge/feature/web/GrailsWebSpec.groovy
Labels: bug

#366 Add grails-app/conf/spring/resources.groovy as a default feature
  grails-forge-core/src/main/java/org/grails/forge/feature/spring/SpringResources.java
  grails-forge-core/src/main/java/org/grails/forge/feature/spring/template/springResources.rocker.raw
  grails-forge-core/src/test/groovy/org/grails/forge/feature/spring/SpringResourcesSpec.groovy
Labels: feature
