Repository grails/grails-forge, pull requests merged in 2024-03, with the labels that each got.

#299 chore(ci): fix release-notes workflow
  .github/workflows/release-notes.yml
Labels: chore, ci, bug, maintenance

#300 refactor(ci): Adjust build process execution in the Snapshot Workflow
  .github/workflows/snapshot.yml
Labels: ci, maintenance, refactor, build

#302 chore(ci): Update Renovate configurations for automatic grouping of d…
  .github/renovate.json
Labels: chore, ci, maintenance

#324 fix(deps): Revert upgrade to asset-pipeline 4.4.0
  .github/renovate.json
  grails-forge-core/src/main/resources/pom.xml
  grails-forge-core/src/test/groovy/org/grails/forge/build/gradle/GradleSpec.groovy
  grails-forge-core/src/test/groovy/org/grails/forge/feature/assetPipeline/AssetPipelineSpec.groovy
Labels: bug, deps, revert
