Repository grails/grails-forge, pull requests merged in 2024-10, with the labels that each got.

#382 ci: Use Java 11 in 6.2.x branch
  .github/workflows/mavenCentral.yml
  .github/workflows/release.yml
  .github/workflows/sdkman.yml
  .github/workflows/snapshot.yml
Labels: ci, maintenance

#385 Include Geb/Selenium dependencies for MacOS Arch64
  grails-cli/src/test/groovy/org/grails/forge/cli/command/CreateControllerCommandSpec.groovy
  grails-cli/src/test/groovy/org/grails/forge/cli/command/CreateDomainClassCommandSpec.groovy
  grails-forge-core/src/main/java/org/grails/forge/feature/test/Geb.java
  test-core/src/test/groovy/org/grails/forge/create/CreateAppSpec.groovy
Labels: ci, maintenance, deps

#392 build: Make spotless also handle single year in license header
  config/spotless.license.java
  grails-forge-core/src/main/java/org/grails/forge/feature/grailsProfiles/GrailsProfiles.java
  grails-forge-core/src/main/java/org/grails/forge/feature/grailsWrapper/GrailsWrapper.java
Labels: maintenance, build

#386 fix(deps): Update to Grails 7, Gradle 8.10.2 and grails-core dependency versions
  gradle.properties
  grails-cli/src/test/groovy/org/grails/forge/cli/CommandSpec.groovy
  grails-forge-analytics-postgres/build.gradle
  grails-forge-api/build.gradle
  grails-forge-core/src/main/java/org/grails/forge/feature/build/gradle/templates/dependencies.rocker.raw
  grails-forge-core/src/main/java/org/grails/forge/feature/micronaut/MicronautInjectGroovy.java
  grails-forge-core/src/main/java/org/grails/forge/feature/other/MicronautHttpClient.java
  grails-forge-core/src/main/resources/pom.xml
  grails-forge-core/src/test/groovy/org/grails/forge/build/gradle/GradleSpec.groovy
  grails-forge-core/src/test/groovy/org/grails/forge/feature/asciidoctor/AsciidoctorSpec.groovy
  grails-forge-core/src/test/groovy/org/grails/forge/feature/assetPipeline/AssetPipelineSpec.groovy
  grails-forge-core/src/test/groovy/org/grails/forge/feature/database/HibernateGormSpec.groovy
  grails-forge-core/src/test/groovy/org/grails/forge/feature/grails/GrailsGradlePluginSpec.groovy
  grails-forge-core/src/test/groovy/org/grails/forge/feature/micronaut/MicronautHttpClientSpec.groovy
  grails-forge-core/src/test/groovy/org/grails/forge/feature/micronaut/MicronautInjectGroovySpec.groovy
  grails-forge-web-netty/build.gradle
  test-core/build.gradle
Labels: bug, deps

#393 ensure grails-wrapper files exist in native grails-forge-cli builds
  grails-forge-core/src/main/resources/META-INF/native-image/org.grails.forge/grails-forge-core/resource-config.json
Labels: bug, maintenance, feature, build

#395 fix(deps): adjust dependencies required for grails 7
  grails-forge-core/src/main/java/org/grails/forge/feature/assetPipeline/AssetPipeline.java
  grails-forge-core/src/main/java/org/grails/forge/feature/build/gradle/templates/buildGradle.rocker.raw
  grails-forge-core/src/main/java/org/grails/forge/feature/build/gradle/templates/settingsGradle.rocker.raw
  grails-forge-core/src/main/java/org/grails/forge/feature/view/GrailsGsp.java
  grails-forge-core/src/main/resources/pom.xml
  grails-forge-core/src/test/groovy/org/grails/forge/build/gradle/GradleSpec.groovy
  grails-forge-core/src/test/groovy/org/grails/forge/feature/assetPipeline/AssetPipelineSpec.groovy
  grails-forge-core/src/test/groovy/org/grails/forge/feature/view/GrailsGspSpec.groovy
Labels: ci, maintenance

#413 New default `geb` feature implementation
  grails-cli/src/test/groovy/org/grails/forge/cli/CommandSpec.groovy
  grails-cli/src/test/groovy/org/grails/forge/cli/command/CreateControllerCommandSpec.groovy
  grails-forge-api/src/test/groovy/org/grails/forge/api/FeatureControllerSpec.groovy
  grails-forge-core/src/main/java/org/grails/forge/feature/test/GebWithTestcontainers.java
  grails-forge-core/src/main/java/org/grails/forge/feature/test/GebWithWebDriverBinaries.java
  grails-forge-core/src/main/java/org/grails/forge/feature/test/template/spock.rocker.raw
  grails-forge-core/src/test/groovy/org/grails/forge/feature/test/GebSpec.groovy
  grails-forge-core/src/test/groovy/org/grails/forge/feature/test/GebWithTestcontainersSpec.groovy
  grails-forge-core/src/test/groovy/org/grails/forge/feature/test/GebWithWebDriverBinariesSpec.groovy
  test-core/src/test/groovy/org/grails/forge/features/scaffolding/ScaffoldingSpec.groovy
Labels: feature
