Repository grails/grails-forge, pull requests merged in 2025-02, with the labels that each got.

#514 Update graalvm image to 23.0.2
  grails-forge-analytics-postgres/build.gradle
  grails-forge-web-netty/build.gradle
Labels: maintenance, build

#519 Revert "Merge pull request #503 from grails/exclude-org.graalvm-dependencies
  grails-forge-core/src/main/java/org/grails/forge/feature/build/gradle/templates/buildGradle.rocker.raw
Labels: ci, maintenance, revert

#526 Update build scan and build cache config
  .github/workflows/gradle.yml
  .github/workflows/mavenCentral.yml
  .github/workflows/next-gcp-deploy.yml
  .github/workflows/prev-gcp-deploy.yml
  .github/workflows/prev-snapshot-gcp-deploy.yml
  .github/workflows/release-gcp-deploy.yml
  .github/workflows/release.yml
  .github/workflows/sdkman.yml
  .github/workflows/snapshot-gcp-deploy.yml
  gradle.properties
  settings.gradle
Labels: maintenance, build

#507 BootStrap servletContext refactoring
  grails-forge-core/src/main/java/org/grails/forge/feature/lang/groovy/bootStrap.rocker.raw
Labels: maintenance, refactor
